version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: kitsu
      POSTGRES_USER: kitsu
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${KITSU_POSTGRES_VOLUME}:/var/lib/postgresql/data

  kitsu:
    image: cgwire/kitsu:latest
    restart: always
    ports:
      - "${WEB_PORT}:80"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=kitsu
      - DATABASE_USER=kitsu
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    volumes:
      - ${KITSU_PREVIEW_VOLUME}:/opt/kitsu/preview
      - ${KITSU_THUMBNAILS_VOLUME}:/opt/kitsu/thumbnails